### ISSUE TITLE
The tutorial is not up-to-date

### ISSUE THREAD

**Issue by fjaviersanchez** [uwssg/LSST-Tutorials#3]
Hi,

I have been trying to use the tutorial to connect to the simulations database and some parts of the code need to be updated because they are using older versions of the repository.

For example:

```
myObsMetadata = ObservationMetaData(unrefractedRA=45.0, unrefractedDec=-10.0,
                                    boundType='circle', boundLength=0.02)
```

Should be now:

```
myObsMetadata = ObservationMetaData(pointingRA=45.0, pointingDec=-10.0,
                                    boundType='circle', boundLength=0.02, mjd=58808)

```

**Comment by danielsf** [comment]
Thanks for letting us know.

I have updated the CatSim tutorials.

Sorry it took so long.
